<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Label="Globals">
	  <WebView2EnableCsWinRTProjection>False</WebView2EnableCsWinRTProjection>
	</PropertyGroup>
	<PropertyGroup>
		<EnableMsixTooling>true</EnableMsixTooling>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<UseWinUI>true</UseWinUI>
		<ApplicationIcon>Assets\Vanara\MFC-App.ico</ApplicationIcon>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<DebugSymbols>false</DebugSymbols>
		<DebugType>portable</DebugType>
		<DefineConstants>TRACE</DefineConstants>
		<Deterministic>true</Deterministic>
		<Optimize>true</Optimize>
		<PublishReadyToRun>true</PublishReadyToRun>
		<PublishTrimmed>false</PublishTrimmed>
		<UseWindowsForms>false</UseWindowsForms>
		<UseWPF>false</UseWPF>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="Resources\**" />
		<EmbeddedResource Remove="Resources\**" />
		<None Remove="Resources\**" />
		<Page Remove="Resources\**" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Microsoft.Win32.SystemEvents" Version="10.0.7" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260317003" />
		<PackageReference Include="Vanara.Core" Version="5.0.4" />
		<PackageReference Include="Vanara.PInvoke.Shell32" Version="5.0.4" />
		<PackageReference Include="Vanara.Windows.Shell" Version="5.0.4" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Templates\" />
		<Folder Include="Vanara\Controls\Shell32\" />
	</ItemGroup>
	<ItemGroup>
		<Content Update="Assets\Vanara\Insert_Amiga-Disk.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Update="Assets\Vanara\WinUi-Sailing.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Vanara\Controls\FeatureTile.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\SettingsPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\NuGetsPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\SamplesPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\StartPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\GitHubPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="DOCS\docs.assets\WinUi-Sailing.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Vanara\Styles\NavButtonStyle.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Vanara\Styles\SidebarControl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Vanara\Controls\Shell32AppBar.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Vanara\Controls\FloatingStatusBar.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<PRIResource Remove="Resources\**" />
	</ItemGroup>
	<ItemGroup>
		<None Remove="Views\AssembliesPage.xaml" />
		<None Remove="Views\ShellPage.xaml" />
		<None Remove="Views\UtilitiesPage.xaml" />
		<None Remove="Views\VoidPage.xaml" />
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Views\VoidPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\ShellPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\AssembliesPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\UtilitiesPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
</Project>
